apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 3111
      targetPort: 3111
      nodePort: 31111  # Accessible on http://localhost:31111
